### PR TITLE
fixes confirmation page

### LINKED ISSUE #63: Confirmation code page does not bring user to home component

### PR DESCRIPTION
**Pull request by bchampp**
closes #63

### CODE REVIEW

File: client/src/components/auth/Register.tsx [hunk 1]
```diff
@@ -110,7 +114,7 @@ export default function SignUp() {
       let cognitoUserInfo = await Auth.currentUserInfo();
       const userId = cognitoUserInfo.username;
 
-      API.post("hour-logger", "/users", {
+      const user = API.post("hour-logger", "/users", {
```
Comment (bchampp) [inline client/src/components/auth/Register.tsx:117]: oops this call should use await

**Review by avalittle — APPROVED** [review]
